# El metodo de k-means

In [1]:
import numpy as np

In [2]:
data = np.random.random(90).reshape(30,3)
data

array([[0.72140593, 0.80511183, 0.77119953],
       [0.11373819, 0.141232  , 0.802686  ],
       [0.2789165 , 0.48888821, 0.31404653],
       [0.60426396, 0.08924538, 0.59332953],
       [0.15859932, 0.37766285, 0.13472831],
       [0.93196198, 0.2129298 , 0.88470126],
       [0.01490132, 0.06070464, 0.33783381],
       [0.66321432, 0.71338107, 0.19634025],
       [0.6401518 , 0.95924623, 0.27224823],
       [0.69409014, 0.32711995, 0.00587086],
       [0.7617945 , 0.46747985, 0.2582601 ],
       [0.50995935, 0.03670555, 0.61797197],
       [0.8302633 , 0.9371693 , 0.62438989],
       [0.27987261, 0.73345135, 0.91729155],
       [0.58731131, 0.64739877, 0.11514224],
       [0.87154624, 0.52729372, 0.74368945],
       [0.95886058, 0.9077638 , 0.44133161],
       [0.11944656, 0.63842209, 0.3397593 ],
       [0.30632481, 0.15597643, 0.23175289],
       [0.74392881, 0.99300716, 0.81204788],
       [0.28969774, 0.77085951, 0.58876421],
       [0.82695372, 0.17949682, 0.49983894],
       [0.

In [4]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
cluster_centers = np.vstack([data[c1], data[c2]])

In [5]:
cluster_centers

array([[0.82695372, 0.17949682, 0.49983894],
       [0.01490132, 0.06070464, 0.33783381]])

In [6]:
from scipy.cluster.vq import vq

In [8]:
vq(data, cluster_centers)

(array([0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 1, 0]),
 array([0.69005147, 0.48201757, 0.50359807, 0.25783045, 0.4029435 ,
        0.40032924, 0.        , 0.63557409, 0.83348762, 0.53240002,
        0.38149742, 0.36719231, 0.7678486 , 0.88341951, 0.65142326,
        0.42709981, 0.74242529, 0.58710379, 0.32443416, 0.87530944,
        0.80174751, 0.        , 0.2313411 , 0.69645539, 0.86455225,
        0.63191265, 0.29048133, 0.73907264, 0.43774961, 0.58542795]))

In [9]:
from scipy.cluster.vq import kmeans

In [11]:
kmeans(data, cluster_centers)

(array([[0.63012368, 0.69513919, 0.5820491 ],
        [0.3832311 , 0.25119188, 0.34953564]]),
 0.38065394163918564)

In [12]:
kmeans(data, 2)

(array([[0.46740117, 0.34989607, 0.32676142],
        [0.61501382, 0.73681344, 0.70125903]]),
 0.37551794753987644)